version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
          timezone: Europe/Oslo
          time: '17:00'
      open-pull-requests-limit: 30
      rebase-strategy: disabled
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: weekly
          timezone: Europe/Oslo
          time: '17:00'
      open-pull-requests-limit: 30
      rebase-strategy: disabled
